baseURL = "https://neimaralvesbarroso.github.io/FisicaSemParticulas/"
languageCode = "pt-br"
title = "Instituto Física Sem Partículas"
theme = "hermit-v2"

[pagination]
  pagerSize = 10

[params]
  description = "Física Sem Partículas com base na Vetorialética"



