baseURL = "http://example.org/"
languageCode = "pt-br"
title = "Instituto Física Sem Partículas"
theme = "PaperMod"

[params]
  author = "Seu Nome"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  disableScrollToTop = false
  comments = false

[menu]
  [[menu.main]]
    identifier = "manifesto"
    name = "Manifesto"
    url = "/manifesto/"
    weight = 10

  [[menu.main]]
    identifier = "teoria"
    name = "Teoria"
    url = "/teoria/"
    weight = 20

  [[menu.main]]
    identifier = "projetos"
    name = "Projetos"
    url = "/projetos/"
    weight = 30

  [[menu.main]]
    identifier = "contato"
    name = "Contato"
    url = "/contato/"
    weight = 40

